name: ddG_with_Boltz

channels:

  - conda-forge
  - defaults
  
dependencies:

  - python=3.10  
  - pip
  
  - pip:

      - -e ./external/boltz_modified
      
      - matplotlib==3.10.8
      - seaborn==0.13.2
