# params.yaml

data_processing:
  raw_data_path: "data/raw/S11304_30_p.csv"
  dataset_type: "standard"
  max_msa_sequences: 1

feature_extraction:
  process_one_by_one: false
  boltz_flags:
    accelerator: "cpu"      
    model: "boltz2"             
    recycling_steps: 3          
    write_full_pae: false
    write_full_pde: false
    cache: boltz_cache
    write_embeddings: true
    skip_run_structure: true
    #num_workers: 2
    #preprocessing-threads: 1


training:
