[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ddg_predictor"
version = "0.1.0"
description = "DDG predictor that uses Boltz embeddings."
authors = [ { name = "Tu Nombre", email = "tu@email.com" } ]
requires-python = ">=3.10,<3.14"
license = { text = "Proprietary" }
readme = "README.md"

dependencies = [
    "torch",            
    "numpy",            
    "pandas",
    "biopython",
    "pyyaml",
    "scikit-learn",
    "openpyxl",
    "tqdm",
    "matplotlib",
    "seaborn",
    "hydra-core",
    "pytorch-lightning",
    "rdkit",
    "dm-tree",
    "requests",
    "types-requests",
    "einops",
    "einx",
    "fairscale",
    "mashumaro",
    "modelcif",
    "wandb",
    "click",
    "scipy",
    "numba",
    "gemmi",
    "chembl_structure_pipeline",
]

[project.optional-dependencies]
dev = ["ruff", "pytest"]
cuda = [
    "cuequivariance_ops_cu12>=0.5.0",
    "cuequivariance_ops_torch_cu12>=0.5.0",
    "cuequivariance_torch>=0.5.0",
]

[project.scripts]
boltz = "boltz.main:cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
target-version = "py310"
lint.select = ["ALL"]
lint.ignore = [ "COM812", "ISC001", "ANN101", "RET504", "S101", "D100", "D104", "PT001", "PT004", "PT005", "PT023", "FBT001", "FBT002", "PLR0913" ]

[tool.ruff.lint.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]

[tool.pytest.ini_options]
markers = [ "slow: marks tests as slow (deselect with '-m \"not slow\"')", "regression" ]
