data_processing:
  raw_data_path: data/raw/P03050.csv
  dataset_type: fireprot
  max_msa_sequences: 1
  output_dir: data/processed/P03050
  msa_output_dir: data/processed/P03050/msas
  queries_dir: data/processed/P03050/boltz_queries
  wt_fasta_filename: wt_sequences.fasta
  mutations_csv_filename: mutations.csv
feature_extraction:
  process_one_by_one: true
  boltz_flags:
    accelerator: cpu
    model: boltz2
    recycling_steps: 0
    write_full_pae: false
    cache: boltz_cache
    write_embeddings: true
    skip_run_structure: true
    write_full_pde: false
    num_workers: 2
    preprocessing-threads: 1
    out_dir: P03050_results
training: null
